name: Trigger Azure Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Azure Pipeline
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_PROJECT_URL }}
          azure-pipeline-name: 'Nandhini-16.sample-node-project'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
